# ./frontend/Dockerfile.dev (DEVELOPMENT)  
FROM node:18-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json ./
COPY package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the React development server port
EXPOSE 3000

# Start the development server
CMD ["npm", "start"]
# ↑ 6 lines for development simplicity ↑