/*
-- Query: select * from skills_key
LIMIT 0, 10000

-- Date: 2025-05-30 20:04
*/
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (1,'Working Memory','Can remember 1 item','Can remember 2 items','Can remember 3 items','Can remember 4 items',0,'Can remember 5 items',3,'Working memory is the ability to remember information for a short time.  It is used when we are thinking about something in the present moment.  It is used when we are thinking about something in the present moment.  It is used when we are thinking about something in the present moment.');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (2,'Attention','Can attend for 1 minute','Can attend for 2 minutes','Can attend for 3 minutes','Can attend for 4 minutes',0,'Can attend for 5 minutes',3,'Attention is the ability to focus on something for a period of time.  It is used when we are thinking about something in the present moment.  It is used when we are thinking about something in the present moment.  It is used when we are thinking about something in the present moment.');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (3,'Audio Processing','Can hear speach in a quiet room','Can hear speach in a room with some background noise','Can hear speach in a room with a lot of background noise','Can hear speach in a room with a lot of background noise and other people talking',0,'Can hear speach in a room with a lot of background noise and other people talking and music playing',3,'Audio processing is the ability to hear and understand speach.  It is used when we are thinking about something in the present moment.  It is used when we are thinking about something in the present moment.  It is used when we are thinking about something in the present moment.');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (4,'Critical Thinking','Can understand the context of a situation','Can understand the context of a situation and the chain of events that lead to the situation','Can understand the context of a situation and the chain of events that lead to the situation and the possible outcomes of the situation','Can understand the context of a situation and the chain of events that lead to the situation and the possible outcomes of the situation and the consequences of the situation',0,'Can understand the context of a situation and the chain of events that lead to the situation and the possible outcomes of the situation and the consequences of the situation and the consequences of the situation',3,'Critical thinking is the ability to understand the context of a situation and the chain of events that lead to the situation and the possible outcomes of the situation and the consequences of the situation.');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (5,'Problem Solving','Can solve a problem with one step','Can solve a problem with two steps','Can solve a problem with three steps','Can solve a problem with four steps',0,'Can solve a problem with five steps',3,'Problem solving is the ability to solve a problem with multiple steps.');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (6,'Active Listening','Can listen to someone and understand what they are saying','Can listen to someone and understand what they are saying and ask questions to clarify what they are saying','Can listen to someone and understand what they are saying and ask questions to clarify what they are saying and to contextualise what they are saying','Can listen to someone and understand what they are saying and ask questions to clarify what they are saying and to contextualise what they are saying and to make predictions about what they are saying',0,'Can listen to someone and understand what they are saying and ask questions to clarify what they are saying and to contextualise what they are saying and to make predictions about what they are saying and to make predictions about what they are saying',3,'Active listening is the ability to listen to someone and understand what they are saying and to ask questions to clarify what they are saying and to contextualise what they are saying and to make predictions about what they are saying.');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (7,'Leadership','The child is able to make decisions and take responsibility for the consequences of those decisions.','The child is able to organise and motivate others to achieve a common goal.','The child is able to make decisions and take responsibility for the consequences of those decisions.','The child is able to organise and motivate others to achieve a common goal.',0,'The child is able to make decisions and take responsibility for the consequences of those decisions.',3,'This skill involves the ability to make decisions and to take responsibility for the consequences of those decisions.  It also involves the ability to organise and motivate others to achieve a common goal.');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (8,'Vocabulary','1.  Uses a limited range of words','2.  Uses a range of words','3.  Uses a wide range of words','4.  Uses a wide range of words and specialist vocabulary',0,'5.  Uses a wide range of words and specialist vocabulary',3,'This skill involves the ability to use a wide range of words and specialist vocabulary.  It also involves the ability to use words in the correct context.');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (9,'Non-verbal communication','1.  Uses a limited range of non-verbal communication','2.  Uses a range of non-verbal communication','3.  Uses a wide range of non-verbal communication','4.  Uses a wide range of non-verbal communication',0,'5.  Uses a wide range of non-verbal communication',3,'This skill involves the ability to use a wide range of non-verbal communication.  It also involves the ability to use non-verbal communication in the correct context.');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (10,'Technology','1.  Uses a limited range of technology','2.  Uses a range of technology','3.  Uses a wide range of technology','4.  Uses a wide range of technology',0,'5.  Uses a wide range of technology',3,'This skill involves the ability to use a wide range of technology.  It also involves the ability to use technology in the correct context.');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (11,'Comprehension','1.  Has a limited understanding of what is being said','2.  Has a good understanding of what is being said','3.  Has a good understanding of what is being said and can answer questions about it','4.  Has a good understanding of what is being said and can answer questions about it',0,'5.  Has a good understanding of what is being said and can answer questions about it',3,'This skill involves the ability to understand what is being said.  It also involves the ability to answer questions about what is being said.');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (12,'Speaking','1.  Speaks in short sentences','2.  Speaks in sentences','3.  Speaks in sentences and can answer questions about what has been said','4.  Speaks in sentences and can answer questions about what has been said',0,'5.  Speaks in sentences and can answer questions about what has been said',3,'This skill involves the ability to speak in sentences.  It also involves the ability to answer questions about what has been said.');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (13,'Reading','1.  25% behind reading age','2.  10% behind reading age','3.  Reading age','4.  10% ahead of reading age',0,'5.  25% ahead of reading age',3,'This skill involves the ability to read.');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (14,'Phonics','1.  Recognises some sounds','2.  Recognises most sounds','3.  Recognises all sounds','4.  Recognises all sounds and can read words where the sounds are not as expected',0,'5.  Recognises all sounds and can read words where the sounds are not as expected',3,'This skill involves the ability to recognise sounds and to blend those sounds together to form words.  It also involves the ability to read words where the sounds are not as expected.');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (15,'Grammar','1.  Uses a limited range of grammar','2.  Uses a range of grammar','3.  Uses a wide range of grammar','4.  Uses a wide range of grammar',0,'5.  Uses a wide range of grammar',3,'This skill involves the ability to use a wide range of grammar.  It also involves the ability to use grammar in the correct context.');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (17,'Spelling','1.  Spelling age','2.  10% behind spelling age','3.  Spelling age','4.  10% ahead of spelling age',0,'5.  25% ahead of spelling age',3,'This skill involves the ability to spell.');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (18,'Handwriting','1.  Writes legibly','2.  Writes legibly and fluently','3.  Writes legibly and fluently','4.  Writes legibly and fluently',0,'5.  Writes legibly and fluently',3,'This skill involves the ability to write legibly and fluently.  It also involves the ability to write legibly and fluently in the correct context.');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (19,'Persuading','The student has demonstrated only a basic grasp of some of the parent skills','The student has demonstrated a basic grasp of some of the parent skills','The student has demonstrated a good grasp of some of the parent skills','The student has demonstrated a very good grasp of most of the parent skills',0,'The student has demonstrated an excellent grasp of all of the parent skills',0,'Persuading is the ability to convince others to accept your point of view.  It involves the ability to research a topic and to present a case for or against the topic.  It also involves the ability to listen to the opposing case and understand the reasons and emotional to respond to it.  It also involves the ability to think on your feet and to respond to questions from the audience.  The key elements of persuading are: Public Speaking, critical thinking, interpersonal skills, listening, thinkin');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (20,'Questioning','The student has demonstrated only a basic grasp of some of the parent skills','The student has demonstrated a basic grasp of some of the parent skills','The student has demonstrated a good grasp of some of the parent skills','The student has demonstrated a very good grasp of most of the parent skills',0,'The student has demonstrated an excellent grasp of all of the parent skills',0,'The skill of questioning requires the ability to understand the area to a depth to lead a discussion on the topic.  It also requires the ability to ask questions that will lead the discussion in a particular direction.  It also requires the ability to listen to the answers and to ask further questions based on the answers.  It also requires the ability to think on your feet and to respond to questions from the audience.  The key elements of questioning are: Public Speaking, critical thinking, in');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (21,'Debating','The student has demonstrated only a basic grasp of some of the parent skills','The student has demonstrated a basic grasp of some of the parent skills','The student has demonstrated a good grasp of some of the parent skills','The student has demonstrated a very good grasp of most of the parent skills',0,'The student has demonstrated an excellent grasp of all of the parent skills',0,'Debating is the ability to argue a point of view in a formal setting.  It involves the ability to research a topic and to present a case for or against the topic.  It also involves the ability to listen to the opposing case and to respond to it.  It also involves the ability to think on your feet and to respond to questions from the audience.  The key elements of debating are: Public Speaking, critical thinking, persuading');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (22,'Poetry','The student has demonstrated only a basic grasp of some of the parent skills','The student has demonstrated a basic grasp of some of the parent skills','The student has demonstrated a good grasp of some of the parent skills','The student has demonstrated a very good grasp of most of the parent skills',0,'The student has demonstrated an excellent grasp of some of the parent skills',0,'The skill of poetry is the abilty to write and analyse poetry.  It involves the ability to understand the meaning of a poem and to convey that meaning to an audience.  It also involves the ability to write poetry that conveys a meaning to an audience.  It also involves the ability to understand the technical aspects of poetry such as rhyme, rhythm, alliteration, assonance, onomatopoeia, metaphor, simile, personification, hyperbole, symbolism, imagery, irony, oxymoron, paradox, pun, allusion, eup');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (24,'Drama','The student has demonstrated only a basic grasp of some of the parent skills','The student has demonstrated a basic grasp of some of the parent skills','The student has demonstrated a good grasp of some of the parent skills','The student has demonstrated a very good grasp of most of the parent skills',0,'The student has demonstrated an excellent grasp of all of the parent skills',0,'This is a composite skill involving the ability to emote and convey emotion to an audience in a number of contexts.  The contexts involve range of roles, range of emotions as well as the tecnical skills involved in film, stage or role playing.');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (25,'Storytelling','The student has demonstrated only a basic grasp of some of the parent skills','The student has demonstrated a basic grasp of some of the parent skills','The student has demonstrated a good grasp of some of the parent skills','The student has demonstrated a very good grasp of most of the parent skills',0,'The student has demonstrated an excellent grasp of all of the parent skills',0,'This is a composite skill involving the ability to tell a story in a number of contexts.  The contexts involve range of roles, range of emotions as well as the tecnical skills involved in film, stage or role playing.');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (57,'Audience Pitching','','','','',NULL,'',0,'');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (58,'Summarizing','','','','',NULL,'',0,'');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (59,'Contextualization','','','','',NULL,'',0,'');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (60,'Deconstruction.','','','','',NULL,'',0,'');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (28,'Explaining','The student has demonstrated only a basic grasp of some of the parent skills','The student has demonstrated a basic grasp of some of the parent skills','The student has demonstrated a good grasp of some of the parent skills','The student has demonstrated a very good grasp of most of the parent skills',0,'The student has demonstrated an excellent grasp of all of the parent skills',0,'The skill of explaining requires the ability to understand the area to a depth on the topic.  It also requires the ability to break down a topic so that it can be understandable to the audience.  It may require the use of analogies, or story telling.  It also requires the ability to listen to the answers and to ask further questions based on the answers.  It also requires the ability to think on your feet and to respond to questions or guage the responses from the audience.');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (30,'Self-awareness','A score of one for self awareness means the student will not question what they do or how they affect others',' Two some questioning of why things happen and see what has triggered their behaviour','Three the student will be able to describe their strengths and weaknesses and how they affect their behaviour','Four the student will be able to describe their strengths and weaknesses and how they affect their behaviour and how they have changed over time and circumstances',0,'Five the student will be able to describe their strengths and weaknesses and how they affect their behaviour and how they have changed over time and circumstances and how they are perceived by others',0,'The skill of self-awareness is the ability to understand your own emotions, what triggers them and how they affect your behaviour.  It involves the ability to understand your own strengths and weaknesses.    It also involves the ability to understand how your emotions are perceived by others.  Assessing the level of self-awareness involves the student being able to describe these things in a way that is consistent with the observations of others and the ability to describe how they have changed over time and circumstances.');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (31,'Self-regulation','1. The student will only be able to describe their emotions after they have acted on them','2. The student will be able to describe their emotions before they act on them, but have limited control of their actins on those emotions','3. The student will be able to describe their emotions before they act on them and will, in the main part, be able to control their actions','4. The student will have some control over their emotional state using such techniques as mindfulness',0,'5. The student will have a high level of control over their emotional state using such techniques as mindfulness and self-motivation',0,'The skill of self-regulation is the ability to control your emotions.  This involves being able to think before you act and the ability to change your emotional state to suit the situation, be it to calm yourself down, to get yourself motivated or to get yourself into a state of mind to perform a task.');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (32,'Empathy','1. The student will not be able to understand the emotions of others','2. The student will be able to understand the emotions of others, but will not be able to understand how their actions or circumstances will affect the emotions of others','3. The student will be able to understand the emotions of others and will be able to understand how their actions or circumstances will affect the emotions of others','4. The student will be able to understand the emotions of others and will be able to understand how their actions or circumstances will affect the emotions of others and how the emotions of others will affect their behaviour',0,'5. The student will be able to understand the emotions of others and will be able to understand how their actions or circumstances will affect the emotions of others and how the emotions of others will affect their behaviour and will be able to use this understanding to influence the emotions of others',0,'The skill of empathy is the ability to understand the emotions of others.  It involves the ability to understand the emotions of others and to understand how your actions or circumstances will affect the emotions of others.  It also involves the ability to understand how the emotions of others will affect their behaviour.');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (33,'Self-Motivation','1. The student will not be able to set goals or to work towards achieving those goals','2. The student will be able to set goals and to work towards achieving those goals, but will not be able to understand the steps that are required to achieve the goal','3. The student will be able to set goals and to work towards achieving those goals and will be able to understand the steps that are required to achieve the goal','4. The student will be able to set goals and to work towards achieving those goals and will be able to understand the steps that are required to achieve the goal and will be able to understand the consequences of not achieving the goal',NULL,'5. The student will be able to set goals and to work towards achieving those goals and will be able to understand the steps that are required to achieve the goal and will be able to understand the consequences of not achieving the goal and will be able to motivate themselves to achieve a goal that is difficult to achieve, or steps that the student does not necessarily enjoy',0,'Self-motivation is the ability to motivate yourself to achieve a goal.  It involves the ability to set goals and to work towards achieving those goals.  It also involves the ability to understand the steps that are required to achieve the goal and to understand the consequences of not achieving the goal.  Strong self-motivation involves the ability to motivate yourself to achieve a goal that is difficult to achieve, or steps that the student does not necessarily enjoy.');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (34,'Graph - Drawing','','','','',NULL,'',0,'');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (35,'Graph - Reading','','','','',NULL,'',0,'');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (36,'Data Tables - Reading','','','','',NULL,'',0,'');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (37,'Data Tables - Producing','','','','',NULL,'',0,'');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (38,'Application of Ideas','','','','',NULL,'',0,'');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (39,'Categorization','','','','',0,'',0,'');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (40,'Data Handling','','','','',0,'',0,'');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (41,'Data Contextualization','','','','',0,'',0,'');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (42,'Description','','','','',0,'',0,'');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (43,'Equipment Handling','','','','',0,'',0,'');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (44,'Experiment Design','','','','',0,'',0,'');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (45,'Experiment Write Up','','','','',0,'',0,'');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (46,'Fine Motor Skills','','','','',0,'',0,'');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (47,'Following Protocols','','','','',0,'',0,'');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (48,'Recall','','','','',0,'',0,'');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (49,'Internet Searching','','','','',0,'',0,'');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (50,'Observation','','','','',0,'',0,'');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (51,'Organizing Information','','','','',0,'',0,'');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (52,'Public Speaking','','','','',0,'',0,'');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (53,'Punctuation','1.  Uses a limited range of punctuation','2.  Uses a range of punctuation','3.  Uses a wide range of punctuation','4.  Uses a wide range of punctuation',0,'5.  Uses a wide range of punctuation',0,'This skill involves the ability to use a wide range of punctuation.  It also involves the ability to use punctuation in the correct context.');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (54,'Social Confidence','','','','',0,'',0,'');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (55,'Understanding Variables','','','','',0,'',0,'');
INSERT INTO `skills_key` (`Skills_keyID`,`Skill_name`,`Criteria1`,`Criteria2`,`Criteria3`,`Criteria4`,`hidden`,`Criteria5`,`DevelopmentAge`,`SkillDescription`) VALUES (56,'Taking Measurements','','','','',0,'',0,'');
