# Builder stage for production
FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build the server binary
RUN CGO_ENABLED=0 GOOS=linux go build -o /server cmd/server/main.go


# Development stage
FROM golang:1.21-alpine AS development

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

# Install air for live reloading
RUN go install github.com/cosmtrek/air@latest

COPY . .

# The default command for the development stage
CMD ["air", "-c", ".air.toml"]


# Final production stage
FROM alpine:latest

WORKDIR /app

# Copy the compiled binary from the builder stage
COPY --from=builder /server .

EXPOSE 8080

# The default command for the production stage
CMD ["./server"]
