#!/bin/bash
#
# Project Index Generator (Dynamic)
# Queries live Docker containers, Weaviate, MongoDB, and the filesystem
# to produce an accurate, up-to-date ecosystem overview.
#
# Usage: ./generate-project-index.sh [output_file]
#
# Also re-ingests all documentation into Weaviate (port 8088).

set -euo pipefail

OUTPUT_FILE="${1:-PROJECT_INDEX.md}"
TIMESTAMP=$(date '+%Y-%m-%d')
CODING="/Users/michaelstewart/Coding"

# ─── Helper functions ───────────────────────────────────────────────

weaviate_count() {
    local port="$1" class="$2"
    curl -s "http://localhost:${port}/v1/graphql" \
        -H 'Content-Type: application/json' \
        -d "{\"query\":\"{ Aggregate { ${class} { meta { count } } } }\"}" 2>/dev/null \
    | python3 -c "
import sys,json
try:
    d=json.load(sys.stdin)
    print(d['data']['Aggregate']['${class}'][0]['meta']['count'])
except: print('—')
" 2>/dev/null || echo "—"
}

mongo_count() {
    local port="$1" db="$2" collection="$3"
    docker exec mongodb mongosh --quiet -u admin -p password123 --authenticationDatabase admin --eval "db.getSiblingDB('${db}').${collection}.countDocuments()" 2>/dev/null || echo "—"
}

file_count() {
    find "$1" -name "*.${2}" 2>/dev/null | grep -v node_modules | grep -v .git | grep -v vendor | grep -v __pycache__ | wc -l | tr -d ' '
}

# ─── Gather live data ──────────────────────────────────────────────

echo "Gathering live data from containers, Weaviate, MongoDB..."

# Weaviate 8081 (humanOS/CHISG)
W81_CHISG=$(weaviate_count 8081 CHISGElement)
W81_LINKS=$(weaviate_count 8081 SkillLink)
W81_COURSES=$(weaviate_count 8081 CourseSkillSuggestions)
W81_DOCS=$(weaviate_count 8081 Documentation)
W81_MEDICAL=$(weaviate_count 8081 MedicalExcerpt)

# Weaviate 8088 (assist)
W88_DOCS=$(weaviate_count 8088 Documentation)
W88_LAO_KW=$(weaviate_count 8088 LAOKeyword)
W88_LAO_LESSON=$(weaviate_count 8088 LAOLesson)
W88_ETP=$(weaviate_count 8088 ETPProfile)
W88_SEMANTIC=$(weaviate_count 8088 SemanticLinks)

# MongoDB counts
MONGO_THESAURUS_GROUPS=$(mongo_count 27018 esp_organizer chisg_thesaurus_groups)
MONGO_THESAURUS_ENTRIES=$(mongo_count 27018 esp_organizer chisg_thesaurus_entries)
# Response matrix is in-memory Go code (response_matrix.go), not MongoDB
MONGO_RESPONSE_MATRIX=18

# LAO database
LAO_DB="${CODING}/LAOMobile/backend/lao.db"
if [ -f "$LAO_DB" ]; then
    LAO_COURSES=$(sqlite3 "$LAO_DB" "SELECT COUNT(*) FROM courses;" 2>/dev/null || echo "?")
    LAO_MODULES=$(sqlite3 "$LAO_DB" "SELECT COUNT(*) FROM modules;" 2>/dev/null || echo "?")
    LAO_TOPICS=$(sqlite3 "$LAO_DB" "SELECT COUNT(*) FROM topics;" 2>/dev/null || echo "?")
    LAO_LESSONS=$(sqlite3 "$LAO_DB" "SELECT COUNT(*) FROM lessons;" 2>/dev/null || echo "?")
    LAO_KEYWORDS=$(sqlite3 "$LAO_DB" "SELECT COUNT(*) FROM keywords;" 2>/dev/null || echo "?")
else
    LAO_COURSES="?" LAO_MODULES="?" LAO_TOPICS="?" LAO_LESSONS="?" LAO_KEYWORDS="?"
fi

# CHISG extraction
EXTRACTION_FILE="${CODING}/assist/data/chisg/extraction_full_sonnet.json"
if [ -f "$EXTRACTION_FILE" ]; then
    EXTRACTION_COUNT=$(python3 -c "
import json
with open('${EXTRACTION_FILE}') as f:
    d = json.load(f)
total_links = sum(len(e.get('links',[])) for e in d.get('extractions',[]))
print(f\"{len(d.get('extractions',[]))} defs, {total_links} links\")
" 2>/dev/null || echo "?")
else
    EXTRACTION_COUNT="not found"
fi

# Docker containers
CONTAINERS=$(docker ps --format '{{.Names}}|{{.Image}}|{{.Status}}' 2>/dev/null | sort)

# File counts
ASSIST_GO=$(file_count "${CODING}/assist" "go")
ASSIST_MD=$(file_count "${CODING}/assist" "md")

echo "Data gathered. Generating index..."

# ─── Write the index ───────────────────────────────────────────────

cat > "$OUTPUT_FILE" << HEADER
# ESP/HumanOS Ecosystem — Project Index

> **Purpose**: Single source of truth for the interconnected educational technology ecosystem.
> **Generated**: ${TIMESTAMP} (auto-generated by \`make index\`)
> **Audience**: Collaborators, employers, AI assistants, and future-me.

---

## Executive Summary

This ecosystem comprises **foundational tools** for education data management and AI-assisted learning, and **products** built on top of them. The core innovation is **CHISG** (Contextualised Hierarchical Iterative Semantic Groupings) — a knowledge-graph methodology for structuring educational content — combined with **ETP** (Emergent Tendency Profiles) for personalised learning.

### Architecture Layers

1. **Foundational Tools** (reusable services, not standalone products):
   - CHISG knowledge graph (Weaviate + semantic links)
   - Skills Map Platform (skills CRUD, course maps, student tracking)
   - humanOS (AI coaching orchestrator with safeguarding)
   - ETP framework (9 biological spectra + voltage calculations + response matrix)

2. **Products** (user-facing applications):
    - LAO (GCSE revision mobile app — App Store approved)
   - ToddlerOS (parent-facing ETP for early years — in development)
   - PrimaryOS (primary-age ETP — concept stage)
   - CareerOS (skills passport — concept stage)
   - ETP Profile (interactive spectrum demo — working)

3. **Concept Demonstrations** (stakeholder engagement):
   - DRB (MAT strategic dashboard — demo with seeded data)

### Primary Value Propositions

1. **For Schools**: Real-time competency tracking, behaviour logging, and strategic oversight
2. **For Students**: Adaptive revision tools with engagement-first design
3. **For Parents**: Understanding and supporting their child's development across the spectra
4. **For Trusts/MATs**: Consolidated financial and estates monitoring with data-driven governance

---

## Projects

### Foundational Tools

| Project | Purpose | Status | Tech Stack |
|---------|---------|--------|------------|
| **CHISG** | Knowledge graph for skills/concepts | ${W81_CHISG} elements, ${W81_LINKS} links | Weaviate, Go, MongoDB |
| **skills-map-platform** | Skills tree, course maps, proficiency | Production (Vultr) | Go, React, MySQL, Weaviate |
| **humanOS** | AI coaching orchestrator + safeguarding | Partial (domain logic complete) | Go, React, Weaviate, Bedrock |
| **ETP Framework** | 9 spectra, voltage calcs, response matrix | Complete (18 entries in Go code) | Go |

### Products

| Project | Purpose | Status | Tech Stack |
|---------|---------|--------|------------|
| **LAOMobile** | GCSE revision app | App Store approved v2.2.1 (${LAO_COURSES} courses, ${LAO_LESSONS} lessons) | React Native, Expo, SQLite |
| **SkillsMarkbookMobile** | Primary teacher competency logging | Early development | React Native, Expo |
| **ETP Profile** | Interactive spectrum demo | Working | React, Go |

### Concept Demonstrations

| Project | Purpose | Status | Tech Stack |
|---------|---------|--------|------------|
| **DRB** | MAT financial & estates dashboard | Demo-functional (seeded data) | Go, React, MongoDB |

### Infrastructure

| Project | Purpose | Status | Tech Stack |
|---------|---------|--------|------------|
| **assist** | Monorepo (docs, API, frontend, deployment) | Active (${ASSIST_GO} Go, ${ASSIST_MD} MD files) | Go, React, Weaviate, Docker |
| **ESPProj** | Legacy MIS features | Migration | Go, React, MySQL |

---

## Live Data (as of ${TIMESTAMP})

### Docker Containers
HEADER

echo '```' >> "$OUTPUT_FILE"
echo "$CONTAINERS" | while IFS='|' read -r name image status; do
    printf "%-25s %-40s %s\n" "$name" "${image:0:40}" "$status" >> "$OUTPUT_FILE"
done
echo '```' >> "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << WEAVIATE

### Weaviate — humanOS instance (port 8081)

| Class | Count | Purpose |
|-------|-------|---------|
| CHISGElement | ${W81_CHISG} | Skills with domain, description, ETP mappings |
| SkillLink | ${W81_LINKS} | Parent→offspring skill relationships |
| CourseSkillSuggestions | ${W81_COURSES} | Subjects, courses, and their skill lists |
| Documentation | ${W81_DOCS} | Indexed project docs (duplicate of 8088) |
| MedicalExcerpt | ${W81_MEDICAL} | LAO revision content |

### Weaviate — assist instance (port 8088)

| Class | Count | Purpose |
|-------|-------|---------|
| Documentation | ${W88_DOCS} | **Primary doc index** — all project MDs |
| LAOKeyword | ${W88_LAO_KW} | GCSE keywords with definitions |
| LAOLesson | ${W88_LAO_LESSON} | Lesson content for revision |
| ETPProfile | ${W88_ETP} | ETP profile snapshots |
| SemanticLinks | ${W88_SEMANTIC} | Concept relationships |

### MongoDB (port 27018, db: esp_organizer)

| Collection | Count | Purpose |
|------------|-------|---------|
| chisg_thesaurus_groups | ${MONGO_THESAURUS_GROUPS} | Scoped Semantic Thesaurus groups |
| chisg_thesaurus_entries | ${MONGO_THESAURUS_ENTRIES} | Thesaurus term entries |
| link_types | — | CHISG link-type definitions |
| sources | — | Extraction source metadata |

### LAO SQLite Database

| Table | Count |
|-------|-------|
| courses | ${LAO_COURSES} (Separate + Trilogy) |
| modules | ${LAO_MODULES} |
| topics | ${LAO_TOPICS} |
| lessons | ${LAO_LESSONS} |
| keywords | ${LAO_KEYWORDS} |

### CHISG Extraction Pipeline

- **Source**: LAO keyword definitions
- **Extraction**: ${EXTRACTION_COUNT}
- **Model**: Claude 3 Sonnet (Bedrock)
- **Rules**: R1–R8, 13-relation controlled vocabulary
- **Output**: \`data/chisg/extraction_full_sonnet.json\`

---

## Core Concepts

### CHISG (Contextualised Hierarchical Iterative Semantic Groupings)
A method of parsing and validating information for vector database ingestion that:
- Maps semantic relationships between skills and concepts
- Enables gap analysis in learning pathways
- Reduces AI hallucinations through grounded knowledge
- Uses 8 extraction rules and 13 controlled relations

**Key files**: \`docs/chisg/CHISG_KNOWLEDGE_GRAPH_ARCHITECTURE.md\`, \`data/chisg/extraction_full_sonnet.json\`

### ETP (Emergent Tendency Profiles)
9 biological spectrums that describe learner tendencies:

| Spectrum | Range |
|----------|-------|
| social_gravity | Introvert ↔ Extrovert |
| energy_directionality | Task focus ↔ Social focus |
| voltage_sensitivity | Calm baseline ↔ High reactivity |
| threat_response | Approach ↔ Avoid |
| care_response | Independent ↔ Nurturing |
| risk_tolerance | Risk-averse ↔ Risk-seeking |
| integrity_logic | Flexible ↔ Rigid principles |
| mirror_neuron_tuning | Low empathy ↔ High empathy |
| orderliness | Spontaneous ↔ Structured |

Plus 2 global moderators: \`pilot_strength\`, \`current_load\`

**Key files**: \`esp-organizer/internal/domain/etp/spectra.go\`

### Scoped Semantic Thesaurus
Maps terminology differences across domains so that semantically equivalent but lexically different terms can be recognized:
- ${MONGO_THESAURUS_GROUPS} groups, ${MONGO_THESAURUS_ENTRIES} entries in MongoDB
- Bridges subjects (e.g., "dissipation" in physics = "inefficiency" in general use)

---

## Data Architecture

### ⚠️ Dual Weaviate System

| Instance | Port | Container | Primary Use |
|----------|------|-----------|-------------|
| humanOS | 8081 | humanos-weaviate-1 | CHISG knowledge graph (skills, links, courses) |
| assist | 8088 | weaviate | Documentation index + LAO data |

### MySQL (port 3307 → 3306)
- **Container**: skills-mysql
- **Database**: dare2lead
- **Purpose**: User accounts, skill assignments, map positions, markbook scores

### MongoDB (port 27018 → 27017)
- **Container**: mongodb
- **Database**: esp_organizer
- **Purpose**: ETP profiles, response matrix, thesaurus

### SQLite (LAO)
- **File**: \`LAOMobile/backend/lao.db\` (bundled in app at \`frontend/assets/lao.db\`)
- **Version**: 1.1.0 (Trilogy + Separate Sciences)

---

## Key File Locations

### Documentation
\`\`\`
assist/docs/
├── PRODUCT_VISION.md
├── TECHNICAL_ARCHITECTURE.md
├── FEATURE_PROJECT_MATRIX.md
├── ROADMAP.md
├── STRATEGIC_PLAYBOOK.md
├── chisg/
│   ├── CHISG_KNOWLEDGE_GRAPH_ARCHITECTURE.md
│   ├── CHISG_TECHNICAL_SPECIFICATION.md
│   └── ETP_DEFINITIONS.md
├── humanos/
│   └── CLASSROOM_DYNAMICS_HARMONICS.md
└── logs/
    ├── DAILY_LOG.md
    └── DECISION_LOG.md
\`\`\`

### Backend (Go)
\`\`\`
assist/esp-organizer/internal/domain/etp/spectra.go  # ETP spectra
assist/esp-organizer/cmd/server/main.go              # API entry
DRB/main.go                                          # Financial API
skills-map-platform/api/main.go                      # Skills API
\`\`\`

### Frontend
\`\`\`
assist/frontend/src/pages/ETPProfilePage.tsx          # ETP profile UI
LAOMobile/frontend/screens/                           # LAO screens
SkillsMarkbookMobile/app/index.tsx                    # SMM entry
\`\`\`

### Scripts & Tools
\`\`\`
humanOS/scripts/ingest_docs.py                        # Doc ingestion → Weaviate 8088
humanOS/scripts/search_docs.py                        # Weaviate doc search
assist/scripts/generate-project-index.sh              # This script
assist/scripts/extract_chisg_links.py                 # CHISG extraction pipeline
assist/scripts/backup-weaviate-to-s3.sh               # Weaviate backup
\`\`\`

---

## Quick Start Commands

\`\`\`bash
# Regenerate this index + re-ingest docs into Weaviate
make index

# Search documentation (BM25)
make search q="CHISG knowledge graph"

# Start all Docker containers
make up

# Run LAO in Expo
cd LAOMobile && make tunnel

# Backup Weaviate
make backup
\`\`\`

---

## Context for Collaborators

### What This Solves
1. **Fragmented Student Data**: No unified view across competency, behaviour, and progress
2. **Teacher Cognitive Load**: Real-time logging impossible with current tools
3. **Trust Blindspots**: MATs lack consolidated financial visibility
4. **Revision Resistance**: Students avoid homework; current tools are intimidating

### The Approach
- **Little and Often**: 10-minute sessions, lowest barrier to entry
- **Sticker Album Metaphor**: Celebrate collection, not completion
- **Grounded AI**: CHISG prevents hallucinations via structured knowledge
- **Eyes-Up Teaching**: Log behaviours without looking at a device
WEAVIATE

echo "✅ Generated: $OUTPUT_FILE ($(wc -l < "$OUTPUT_FILE") lines)"
