#!/bin/bash

# generate_tree.sh
# This script generates a tree view of the project structure and saves it to a Markdown file.
# It excludes common directories and files that add noise to the output.

# Directories/files to exclude from the tree view.
# Use '|' to separate multiple patterns.
EXCLUDE_PATTERN=".git|vendor|bin|.vscode|.idea|node_modules|.DS_Store|go.work.sum|dist"

# The output file where the tree structure will be saved.
OUTPUT_FILE="PROJECT_STRUCTURE.md"

# --- Script Start ---

# Check if the tree command is installed
if ! command -v tree &> /dev/null
then
    echo "Error: 'tree' command not found."
    echo "Please install it to continue."
    echo "On macOS: brew install tree"
    echo "On Debian/Ubuntu: sudo apt-get install tree"
    exit 1
fi

echo "🌳 Generating project structure..."

# Create the header for the Markdown file
echo "# Project Structure" > "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "This file is auto-generated by the \`scripts/generate_tree.sh\` script." >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo '```' >> "$OUTPUT_FILE"

# Generate the tree, excluding specified patterns, and append to the file
# --dirsfirst lists directories before files for better readability.
tree -I "$EXCLUDE_PATTERN" --dirsfirst . >> "$OUTPUT_FILE"

# Close the code block
echo '```' >> "$OUTPUT_FILE"

echo "✅ Project structure successfully saved to $OUTPUT_FILE"

# --- End of Script ---
